akronsystem/MobileSchoolAPI

MobileSchoolAPI/BusinessLayer/GetTeacherInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/Controllers/DashboardController.cs
MobileSchoolAPI/Models/GetUserId.cs
MobileSchoolAPI/Models/STUDENTINFO.cs
MobileSchoolAPI/Models/VW_EMPLOYEE.cs
MobileSchoolAPI/Models/VW_STUDENT_INFO.cs

changes in : GetTeacherInfoBusiness
:GetUserIdBusiness
: STUDENTINFO_BUSINESS
: DashboardController, GetUserId , studentinfo,vw_employee,vw_student_info

Dashboard Controller changes

---

MobileSchoolAPI/BusinessLayer/GetTeacherInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/Controllers/TERMLISTController.cs
MobileSchoolAPI/Models/GetUserId.cs
MobileSchoolAPI/Models/TermListResult.cs

Dashboard and TermList Controller Changes
files - GetTeacherInfoBusiness
-GetUserIdBusiness, STUDENTINFO_BUSINESS, TERMLISTController,GetUserId,TermListResult

Dashboard and TermList Controller Changes

---

.gitignore
MobileSchoolAPI/BusinessLayer/ClassTeacherData.cs
MobileSchoolAPI/DAL/SchoolContext.cs
MobileSchoolAPI/Models/CheckUsernamePassword.cs
MobileSchoolAPI/Models/VWATTENDANCEBYDATESTUDENT.cs
MobileSchoolAPI/Models/VW_GET_USER_TYPE.cs

Added class file CheckUsernamePassword in Models.
Added a validation for monthly attendance check to show attendance is marked or not.

Added new function to match userid and password

---

MobileSchoolAPI/BusinessLayer/ClassTeacherData.cs
MobileSchoolAPI/Controllers/CLASSTEACHERController.cs
MobileSchoolAPI/Controllers/ClassTeacherController.cs
MobileSchoolAPI/Models/CheckUsernamePassword.cs

The password was checked after encryption. Changed it since it is already passed by encrypting.
also return type of ClassTeacherController function changed when error is returned.

Change in CheckUsernamePassword function

---

MobileSchoolAPI/Controllers/DivisionListController.cs
MobileSchoolAPI/Controllers/HomeWorkController.cs
MobileSchoolAPI/Controllers/NotificationController.cs
MobileSchoolAPI/Controllers/SubjectListController.cs
MobileSchoolAPI/Models/DivisionListByUserResult.cs
MobileSchoolAPI/Models/DivisionListResult.cs
MobileSchoolAPI/ResultModel/StdListResult.cs

Changed type of IsSucess from string to bool

Changes in result File

---

MobileSchoolAPI/Controllers/LoginController.cs

MESSAGE WHEN USERID OR PASSWORD IS WRONG LOGINCONTROLLER

MESSAGE WHEN USERID OR PASSWORD IS WRONG LOGINCONTROLLER

---

MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GetDivisionInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetStandardList.cs
MobileSchoolAPI/BusinessLayer/GetSubjectListBusiness.cs
MobileSchoolAPI/Controllers/DivisionListController.cs
MobileSchoolAPI/Controllers/SubjectListController.cs
MobileSchoolAPI/DAL/SchoolContext.cs
MobileSchoolAPI/Models/VIEWDIVISIONLIST.cs
MobileSchoolAPI/Models/VIEWDIVISIONLISTBYSTUDENT.cs
MobileSchoolAPI/Models/VIEWSTUDENTDIVISION.cs

Checked Invalid UserId Ids in DivisionList And StandardList

Changes in DivisionList and StandardList

---

MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GETSTUDENTATTBL.cs
MobileSchoolAPI/BusinessLayer/GETTERMLISTBL.cs
MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/ATTENDANCEController.cs
MobileSchoolAPI/Controllers/HomeWorkController.cs
MobileSchoolAPI/Controllers/TERMLISTController.cs
MobileSchoolAPI/Controllers/UserWiseAttendanceController.cs
MobileSchoolAPI/ResultModel/AttendanceResult.cs

Changes the reyurn type of functions to boolean type and displayed proper error messages on exceptions.

Changed The return result types of Function

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs

Changes in Homeworkbusinesslayer

Neeta and Ankita merged changes

---

MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GetDivisionInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetStandardList.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/DAL/ConcreateContext.cs
MobileSchoolAPI/Models/GetUserId.cs
MobileSchoolAPI/ParamModel/PARAMSTD.cs
MobileSchoolAPI/ParamModel/ParamDateWiseAttendance.cs

Done Changes in all class files for multiple connection strings

Changes in Business Layer for Run time get the Context Object

---

MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/Controllers/HomeWorkController.cs
MobileSchoolAPI/MobileSchoolAPI.csproj
MobileSchoolAPI/ParamModel/ParamHomeWorkAll.cs

Created new API to show homework from fromdate to todate.

New API For ShowHomeWorkAll

---

MobileSchoolAPI/BusinessLayer/DeviceBusinessLayer.cs
MobileSchoolAPI/Controllers/ATTENDANCEController.cs
MobileSchoolAPI/Controllers/LoginController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/TBLDeviceRegistration.cs
MobileSchoolAPI/Models/TBLUSERLOGIN.cs
MobileSchoolAPI/Models/VW_DEVICE.cs
MobileSchoolAPI/ParamModel/ParamDevice.cs
MobileSchoolAPI/ParamModel/ParamLogin.cs

Login Device Id and Device Type

Login Device Id and Device Type

---

MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/UserWiseAttendanceController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/VW_DATEWISECLASSSTATUSATTENDANCE.cs

Showing the Student Wise List And Attendance Status of selected Date To Class Teacher.
Added New Function in UserWiseAttendance BL file.
Added New Function in UserWiseAttendace  Controller.
Added New View VW_DATEWSIECLASSSTATUSATTENDACE

New Update For Showing Studentwise Attendance Status To Class Teacher

---

MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Models/VW_DATEWISECLASSSTATUSATTENDANCE.cs

The Student List Was not sorted rollno. wise.
Changes done in UserWiseAttendance in BL class.

List Sorted Roll NO. Wise

---

MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/Controllers/NotificationController.cs
MobileSchoolAPI/Models/VIEWNOTIFICATION.cs

ViewNotification-Resolved Problem of Duplication Records in Listing
UpdateNotification-Result is in JSON format

Chnages in Notification Controller

---

MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/Controllers/NotificationController.cs

Proper Error Message for Invalid User

View Notification Changes

---

MobileSchoolAPI/BusinessLayer/BirthdayBusiness.cs
MobileSchoolAPI/Controllers/DashboardController.cs
MobileSchoolAPI/Models/ViewGetEmployeeBirthDetail.cs

ADDED GetTodayEmployeeBirthDetails() in Dashboard Controller for Employee Birth Details
- created View -  ViewGetEmployeeBirthDetails

ADDED GetTodayEmployeeBirthDetails() in Dashboard Controller for Employee Birth Details

---

MobileSchoolAPI/BusinessLayer/ClassTeacherData.cs
MobileSchoolAPI/BusinessLayer/DeviceBusinessLayer.cs
MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GETSTUDENTATTBL.cs
MobileSchoolAPI/BusinessLayer/GETTERMLISTBL.cs
MobileSchoolAPI/BusinessLayer/GetDivisionInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetExamScheduleBL.cs
MobileSchoolAPI/BusinessLayer/GetGalleryDetailBL.cs
MobileSchoolAPI/BusinessLayer/GetStandardList.cs
MobileSchoolAPI/BusinessLayer/GetSubjectListBusiness.cs
MobileSchoolAPI/BusinessLayer/GetTeacherInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/BusinessLayer/TestTypeBL.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/CLASSTEACHERController.cs
MobileSchoolAPI/Controllers/ClassTeacherController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/Result.cs

Chnages All error messages in all API

Check Error Message in All API

---

MobileSchoolAPI/BusinessLayer/BirthdayBusiness.cs
MobileSchoolAPI/BusinessLayer/InstituteBusiness.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/ViewGetEmployeeBirthDetail.cs
MobileSchoolAPI/Models/ViewGetTodayBirthDetail.cs

changes in following Files
- BirthdayBusiness,  InstituteBusiness, SchoolMainContext,
ViewGetEmployeeBirthDetail, ViewGetTodayBirthDetail

Birthday Problem Solved

---

MobileSchoolAPI/BusinessLayer/GetExamScheduleBL.cs
MobileSchoolAPI/BusinessLayer/GetGalleryDetailBL.cs
MobileSchoolAPI/ResultModel/GalleryResult.cs

Changes related to Gallary Images

Changes related to Gallary Images

---

MobileSchoolAPI/BusinessLayer/ClassTeacherData.cs
MobileSchoolAPI/BusinessLayer/DeviceBusinessLayer.cs
MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GETSTUDENTATTBL.cs
MobileSchoolAPI/BusinessLayer/GETTERMLISTBL.cs
MobileSchoolAPI/BusinessLayer/GetDivisionInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetStandardList.cs
MobileSchoolAPI/BusinessLayer/GetSubjectListBusiness.cs
MobileSchoolAPI/BusinessLayer/GetTeacherInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/BusinessLayer/TestTypeBL.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/LoginController.cs

Chnaged all Success messages in all BusinessLayer Methods

Chnages in IsSuccess Message

---

MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/Controllers/LoginController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/TBLUSERLOGIN.cs
MobileSchoolAPI/Models/View_UnreadNotificationCount.cs

Added Notification count of homework

Added Notification count of homework

---

MobileSchoolAPI/BusinessLayer/BirthdayBusiness.cs
MobileSchoolAPI/BusinessLayer/ClassTeacherData.cs
MobileSchoolAPI/BusinessLayer/DeviceBusinessLayer.cs
MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/GETSTUDENTATTBL.cs
MobileSchoolAPI/BusinessLayer/GETTERMLISTBL.cs
MobileSchoolAPI/BusinessLayer/GetDivisionInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetExamScheduleBL.cs
MobileSchoolAPI/BusinessLayer/GetGalleryDetailBL.cs
MobileSchoolAPI/BusinessLayer/GetStandardList.cs
MobileSchoolAPI/BusinessLayer/GetSubjectListBusiness.cs
MobileSchoolAPI/BusinessLayer/GetTeacherInfoBusiness.cs
MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/BusinessLayer/InstituteBusiness.cs
MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/BusinessLayer/TestTypeBL.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/CLASSTEACHERController.cs
MobileSchoolAPI/Controllers/ClassTeacherController.cs
MobileSchoolAPI/Controllers/LoginController.cs
MobileSchoolAPI/Models/TermListResult.cs

Chnaged Result Message in all BusinessLayer Methods

Chnages in Result Message

---

MobileSchoolAPI/BusinessLayer/GetUserIdBusiness.cs
MobileSchoolAPI/BusinessLayer/InstituteBusiness.cs
MobileSchoolAPI/BusinessLayer/LoginManager.cs
MobileSchoolAPI/BusinessLayer/STUDENTINFO_BUSINESS.cs
MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/Controllers/LoginController.cs
MobileSchoolAPI/DAL/ASMSchoolContext.cs
MobileSchoolAPI/DAL/ASYSCHOOLSchoolContext.cs
MobileSchoolAPI/DAL/ConcreateContext.cs
MobileSchoolAPI/DAL/NMESSchoolContext.cs
MobileSchoolAPI/MobileSchoolAPI.csproj
MobileSchoolAPI/Models/VW_EMPLOYEE.cs
MobileSchoolAPI/Models/VW_STUDENT_INFO.cs
MobileSchoolAPI/ResultModel/ResultLogin.cs
MobileSchoolAPI/Web.config

Change in Login

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/Web.config

Changes related to Attendance Sms

Changes related to Attendance Sms

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs

Added Different  School's short URL and SMS Configuration API

Changes in SMS Configuration

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/Controllers/HomeWorkController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/MobileSchoolAPI.csproj
MobileSchoolAPI/Models/TBLMSGHISTORY.cs
MobileSchoolAPI/Models/Vw_ATTENDANCECHECK.cs

Saved Record in TBLMSGHISTORY after sending sms

SMS SEND CHANGES

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/TBLASSIGNCLASSTEACHER.cs

Checked Valid DivisionID of that perticuler class teacher

Attendance Chnages

---

MobileSchoolAPI/BusinessLayer/UserWiseAttendance.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/TBLASSIGNCLASSTEACHER.cs
MobileSchoolAPI/Models/VW_DATEWISECLASSSTATUSATTENDANCE.cs

Added Divisionid Column in VIew and Matched it in the query.
Matched the divisionid of class teacher with the attendance record's divisionid.

View Attendance Changes

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs

Changed in Homeworkbusiness layer to stop sending SMS of attendance to New Model School.

Commented SMS for New Model School

---

MobileSchoolAPI/BusinessLayer/GETHOMEWORK.cs
MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
MobileSchoolAPI/BusinessLayer/NotificationBusiness.cs
MobileSchoolAPI/Controllers/NotificationController.cs
MobileSchoolAPI/DAL/SchoolMainContext.cs
MobileSchoolAPI/Models/DivisionListResult.cs
MobileSchoolAPI/Models/TBLASSIGNCLASSMASTER.cs
MobileSchoolAPI/Models/VIEWGENERALNOTIFICATION.cs
MobileSchoolAPI/Models/VIEWNOTIFICATIONGEN.cs
MobileSchoolAPI/Web.config

Added New API
ViewEventNotification
ViewHomeworkNotification
ViewGeneralNotification
ViewAllNotification
Chnages of file upload using FTP in TestUpload API
Added Multiple Base Url For FTP file upload and url of uploaded file.

Chnages of homework and notification

---

SoapMobileWebService/App_Code/SoapContext.cs
SoapMobileWebService/App_Code/TBLFEDERALREQUESTDETAIL.cs
SoapMobileWebService/App_Code/View_GETFEDERALREQUESTID.cs
SoapMobileWebService/App_Code/View_GetConcessionDetails.cs
SoapMobileWebService/App_Code/View_GetFeeData.cs
SoapMobileWebService/App_Code/View_GetFeeSettings.cs
SoapMobileWebService/App_Code/View_GetPaidFees.cs
SoapMobileWebService/App_Code/getbilldetailsservice.cs
SoapMobileWebService/Web.config

Added the getbilldetailsoperation function. Added Views View_GetFeeData, View_GetFeeSettings,View_GetPaidFees

Changes Regarding SOAP API

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs

Corrected the bug in service getbilldetailoperation

Change in Getbilldetailsserviceperation

---

SoapMobileWebService/App_Code/SoapContext.cs
SoapMobileWebService/App_Code/TBLFEDERALREQUESTDETAIL.cs
SoapMobileWebService/App_Code/TBLFEECOLLECTIONNKV.cs
SoapMobileWebService/App_Code/TBLFEECOLLECTIONNKVSFEDERAL.cs
SoapMobileWebService/App_Code/TBLRECEIPTTABLENEW.cs
SoapMobileWebService/App_Code/TBLRECEIPTTABLENEWFEDEREAL.cs
SoapMobileWebService/App_Code/View_GetFeeSettings.cs
SoapMobileWebService/App_Code/View_GetReceiptNo.cs
SoapMobileWebService/App_Code/View_GetSudentStandard.cs
SoapMobileWebService/App_Code/getbilldetailsservice.cs
SoapMobileWebService/App_Code/updatebilldetailsservice.cs

Added entity models required to updatebilldetails.
Modified output parameters of getbilldetailsservice.

Added updatebilldetailsoperation

---

MobileSchoolAPI/BusinessLayer/Homeworkbussinesslayer.cs
SoapMobileWebService/App_Code/updatebilldetailsservice.cs

Added one parameter for updatebilldetailsservice as per word document

Added a parameter for updatebilldetailsservice

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs

Removed the Parameter and passed the system date directly from code behind as per the bank requirement in getbilldeatilsservice.cs

Removed Payment Date Parameter in getbilldeatilsservice

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs
SoapMobileWebService/Web.config

Changes regarding getbilldetails to check error stack

Changes in getbilldetails to trace error stack

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs

Change regarding printing stacktrace of the exception

change in getbilldetailsservice

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs
SoapMobileWebService/Web.config

Changes in getbilldetailsservice regarding date exception and added globalization part in web.config

getbilldetailsservice and web.config changes

---

SoapMobileWebService/App_Code/getbilldetailsservice.cs

change in getbilldeatsilsservice
